/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CampusCredNFT } from './CampusCredNFT.js';
export * as factories from './factories/index.js';
export { CampusCredNFT__factory } from './factories/CampusCredNFT__factory.js';